version: '3'

services:
  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    build:
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./frontend:/app/
      - frontend-nodemodules:/app/node_modules

  api-gateway:
    extends:
      file: docker-compose.yml
      service: api-gateway
    depends_on:
      - account

  account-db:
    extends:
      file: docker-compose.yml
      service: account-db

  account:
    extends:
      file: docker-compose.yml
      service: account
    volumes:
      - ./account:/app/
      - account-nodemodules:/app/node_modules
    depends_on:
      - account-db

volumes:
  frontend-nodemodules: {}
  account-nodemodules: {}
  postgres_data: {}
