version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./prod.Dockerfile
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    environment:
      MODE: ${MODE}
      FRONTEND_PORT: ${FRONTEND_PORT}
      API_GATEWAY_PORT: ${API_GATEWAY_PORT}
    image: 'erenes1/frontend:${DOCKER_TAG}'

  api-gateway:
    build: ./api-gateway
    ports:
      - '${API_GATEWAY_PORT}:${API_GATEWAY_PORT}'
    environment:
      ACCOUNT_PORT: ${ACCOUNT_PORT}
      API_GATEWAY_PORT: ${API_GATEWAY_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_KEYID: ${JWT_KEYID}
    depends_on:
      - account
    image: 'erenes1/api-gateway:${DOCKER_TAG}'

  account:
    build: ./account
    ports:
      - '${ACCOUNT_PORT}:${ACCOUNT_PORT}'
    environment:
      MODE: ${MODE}
      ACCOUNT_PORT: ${ACCOUNT_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_KEYID: ${JWT_KEYID}
    image: 'erenes1/account:${DOCKER_TAG}'
