version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./prod.Dockerfile
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    environment:
      MODE: ${MODE}
      FRONTEND_PORT: ${FRONTEND_PORT}
      API_GATEWAY_PORT: ${API_GATEWAY_PORT}

  api-gateway:
    build: ./api-gateway
    ports:
      - '${API_GATEWAY_PORT}:${API_GATEWAY_PORT}'
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      API_GATEWAY_PORT: ${API_GATEWAY_PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    environment:
      MODE: ${MODE}
      BACKEND_PORT: ${BACKEND_PORT}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
