name: docker-compose-actions-workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      MODE: ${{ secrets.MODE }}
      BACKEND_PORT: ${{ secrets.BACKEND_PORT }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      API_GATEWAY_PORT: ${{ secrets.API_GATEWAY_PORT }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      DOCKER_TAG: ${{ secrets.DOCKER_TAG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: docker-compose build

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker images
        if: github.ref == 'refs/heads/main'
        run: docker-compose push
